### ISSUE TITLE
Current Seravo Plugin master tip breaks wp-test: PHP Fatal error:  Uncaught Error: Class 'Seravo\Domains' not found

### ISSUE THREAD

**Issue by ottok** [Seravo/seravo-plugin#292]
While running `wp-test` with latest Seravo Plugin git master:
```
Acceptance Tests (2) ------------------------------------------------------------------------------------
⏺ Recording ⏺ step-by-step screenshots will be saved to /data/reports/tests/
Directory Format: record_5d9f917eb3919_{filename}_{testname} ----
✔ SeravoCheckWPHomeCest: Try to open home (1.64s)
✖ SeravoCheckWPLoginCest: Try to login and access wp admin (38.57s)
---------------------------------------------------------------------------------------------------------
⏺ Records saved into: file:///data/reports/tests/records.html


Time: 40.83 seconds, Memory: 12.00MB

There was 1 failure:

---------
1) SeravoCheckWPLoginCest: Try to login and access wp admin
 Test  seravo/acceptance/SeravoCheckWPLoginCest.php:tryToLoginAndAccessWPAdmin
 Step  See element "#wpadminbar"
 Fail  Browser console shows errors: 
SEVERE: https://zabbixtest.tre-test.seravo.co/wp-admin/ - Failed to load resource: the server responded with a status of 500 ()

Scenario Steps:

 14. $I->checkBrowserConsole() at seravo/acceptance/SeravoCheckWPLoginCest.php:53
 13. $I->makeScreenshot("wp-admin") at seravo/acceptance/SeravoCheckWPLoginCest.php:52
 12. $I->amOnPage("/wp-admin/") at seravo/acceptance/SeravoCheckWPLoginCest.php:51
 11. $I->getConsoleLog() at seravo/acceptance/SeravoCheckWPLoginCest.php:47
 10. $I->amOnPage("/wp-login.php?seravotest-auth-bypass=c50c8c78f97cf65de24a13256b87cbe46d02e2fbbf5a...") at seravo/acceptance/SeravoCheckWPLoginCest.php:44
 9. $I->seeElement("#wpadminbar") at seravo/acceptance/SeravoCheckWPLoginCest.php:40

Artifacts:

Png: /data/reports/tests/SeravoCheckWPLoginCest.tryToLoginAndAccessWPAdmin.fail.png
Html: /data/reports/tests/SeravoCheckWPLoginCest.tryToLoginAndAccessWPAdmin.fail.html

FAILURES!
Tests: 2, Assertions: 4, Failures: 1.


test-fi@test-fi_1ddf51:/data/home/test-fi$ cat /data/log/php-error.log

[10-Oct-2019 20:16:38 UTC] PHP Fatal error:  Uncaught Error: Class 'Seravo\Domains' not found in /data/wordpress/htdocs/wp-content/mu-plugins/seravo-plugin/modules/toolbox.php:70
Stack trace:
#0 /data/wordpress/htdocs/wordpress/wp-includes/class-wp-hook.php(286): Seravo\Toolbox::register_toolbox_subpages('')
#1 /data/wordpress/htdocs/wordpress/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#2 /data/wordpress/htdocs/wordpress/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#3 /data/wordpress/htdocs/wordpress/wp-admin/includes/menu.php(154): do_action('admin_menu', '')
#4 /data/wordpress/htdocs/wordpress/wp-admin/menu.php(309): require_once('/data/wordpress...')
#5 /data/wordpress/htdocs/wordpress/wp-admin/admin.php(152): require('/data/wordpress...')
#6 /data/wordpress/htdocs/wordpress/wp-admin/index.php(10): require_once('/data/wordpress...')
#7 {main}
  thrown in /data/wordpress/htdocs/wp-content/mu-plugins/seravo-plugin/modules/toolbox.php on line 70
```

**Comment by ottok** [comment]
Steps to reproduce:
- create a network site, ensure there is a normal seravo-test user account
- log in as seravo-test user, end up at `<site>/wp-admin/user`
- remove "user" from url and try to open `/wp-admin`
-> error 500
