### ISSUE TITLE
Flow-Flow thirdparty plugin hack needed

### ISSUE THREAD

**Issue by simoke** [Seravo/seravo-plugin#345]
As discussed in https://github.com/Seravo/wp-palvelu/issues/447, we would need a "hack" for commercial Flow-Flow plugin to flush cache when Flow-Flow raises database error. For some reason, Flow-Flow repeatedly fails to connect site's database and gives "Flow-Flow plugin encountered database connection error". The main problem is that the error message will be cached and site throws the error with every page load for some time.

We also recognize the error in Zabbix and sysadmin on-call / in-charge must flush cache manually when this happens.

Error in php-error.log (site leipatuossa-fi-s.seravo.com):
```
[27-Mar-2020 08:01:30 UTC] flow\db\SafeMySQL: 2006 MySQL server has gone away
[27-Mar-2020 08:01:30 UTC] #0 /data/wordpress/htdocs/wp-content/plugins/flow-flow/includes/db/SafeMySQL.php(125): flow\db\SafeMySQL->error('flow\\db\\SafeMyS...')
#1 /data/wordpress/htdocs/wp-content/plugins/flow-flow/includes/db/FFDB.php(46): flow\db\SafeMySQL->__construct(Array)
#2 /data/wordpress/htdocs/wp-content/plugins/flow-flow/includes/db/FFDB.php(38): flow\db\FFDB::create()
#3 /data/wordpress/htdocs/wp-content/plugins/flow-flow/includes/db/FFDB.php(136): flow\db\FFDB::conn()
#4 /data/wordpress/htdocs/wp-content/plugins/flow-flow/includes/db/LADBManager.php(406): flow\db\FFDB::getOption('wp_ff_options', 'flow_flow_regis...', false, false)
#5 /data/wordpress/htdocs/wp-content/plugins/flow-flow/includes/core/LARemoteUpdater.php(14): flow\db\LADBManager->getOption('registration_id')
#6 /data/wordpress/htdocs/wp-content/plugins/flow-flow/includes/FlowFlowActivator.php(171): la\core\LARemoteUpdater->__construct(Array)
#7 /data/wordpress/htdocs/wp-content/plugins/flow-flow/includes/core/LAActivatorBase.php(82): flow\FlowFlowActivator->beforePluginLoad()
#8 /data/wordpress/htdocs/wp-content/plugins/flow-flow/includes/core/LAActivatorFacade.php(30): la\core\LAActivatorBase->loadPlugin()
#9 /data/wordpress/htdocs/wordpress/wp-includes/class-wp-hook.php(288): la\core\LAActivatorFacade->load_plugins('')
#10 /data/wordpress/htdocs/wordpress/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array)
#11 /data/wordpress/htdocs/wordpress/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#12 /data/wordpress/htdocs/wordpress/wp-settings.php(392): do_action('plugins_loaded')
#13 /data/wordpress/htdocs/wp-config.php(106): require_once('/data/wordpress...')
#14 /data/wordpress/htdocs/wordpress/wp-load.php(42): require_once('/data/wordpress...')
#15 /data/wordpress/htdocs/wordpress/wp-blog-header.php(13): require_once('/data/wordpress...')
#16 /data/wordpress/htdocs/index.php(6): require('/data/wordpress...')
#17 {main}
```
![image](https://user-images.githubusercontent.com/25475688/77755040-23894e00-7035-11ea-8e3c-ce4f0af449f6.png)

**Comment by JoosuaKoskinen** [comment]
In `includes/db/SafeMySQL.php` Flow-Flow has an option to create an `wpdb` instance instead of connecting to MySQL by itself. If `wpdb` is used, WordPress properly responds with HTTP 500 (not cached) and "there has been a critical error on your website" instead of HTTP 200 and leaking db credentials.

So could just use `define('FF_USE_WPDB', true);` for sites with Flow-Flow. Not sure if this would work in real situation though.
