### ISSUE TITLE
API error handling on Upkeep and Sitestatus pages

### ISSUE THREAD

**Issue by Moppa5** [Seravo/seravo-plugin#548]
**Describe the bug**
Seems that Upkeep and Sitestatus pages lack the proper error handling when API call fails completely. This causes several excessive errors on php-error.log. I'm just documenting it here so that we might as well make a quick fix or fix it on Up-To-Date project when rewriting. 

```
[17-Jun-2021 06:47:01 UTC] PHP Fatal error:  Uncaught Error: Cannot use object of type WP_Error as array in /data/wordpress/htdocs/wp-content/mu-plugins/seravo-plugin/modules/upkeep.php:202
Stack trace:
#0 /data/wordpress/htdocs/wp-content/mu-plugins/seravo-plugin/lib/postbox/handler.php(325): Seravo\Upkeep::site_status_postbox()
#1 /data/wordpress/htdocs/wp-content/mu-plugins/seravo-plugin/lib/postbox/handler.php(239): Seravo\Postbox\Seravo_Postbox_Factory->display_single_postbox('site-status', Array)
#2 /data/wordpress/htdocs/wp-content/mu-plugins/seravo-plugin/lib/postbox/handler.php(280): Seravo\Postbox\Seravo_Postbox_Factory->do_postboxes('tools_page_upke...', 'normal')
#3 /data/wordpress/htdocs/wp-content/mu-plugins/seravo-plugin/lib/postbox/handler.php(388): Seravo\Postbox\Seravo_Postbox_Factory->display_postboxes_page('two_column')
#4 /data/wordpress/htdocs/wordpress/wp-includes/class-wp-hook.php(292): Seravo\Postbox\seravo_two_column_postboxes_page('')
#5 /data/wordpress/htdocs/wordpress/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters('', Array)
#6 /data/wordpress/htdocs/wordpress/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#7 /data/wordpress/htdocs/wordpress/wp-admin/admin.php(259): do_action('tools_page_upke...')
#8 /data/wordpress/htdocs/wordpress/wp-admin/tools.php(40): require_once('/data/wordpress...')
#9 {main}
  thrown in /data/wordpress/htdocs/wp-content/mu-plugins/seravo-plugin/modules/upkeep.php on line 202
[17-Jun-2021 06:47:01 UTC] SWD API () error 401: 
[17-Jun-2021 06:47:01 UTC] SWD API () error 401: 
[17-Jun-2021 06:48:25 UTC] SWD API () error 401: 
[17-Jun-2021 06:48:25 UTC] SWD API (/shadows) error 401: 
[17-Jun-2021 06:48:25 UTC] SWD API () error 401: 
[17-Jun-2021 06:48:25 UTC] PHP Fatal error:  Uncaught Error: Cannot use object of type WP_Error as array in /data/wordpress/htdocs/wp-content/mu-plugins/seravo-plugin/modules/sitestatus.php:409
Stack trace:
#0 /data/wordpress/htdocs/wp-content/mu-plugins/seravo-plugin/lib/postbox/handler.php(325): Seravo\Site_Status::seravo_site_info()
#1 /data/wordpress/htdocs/wp-content/mu-plugins/seravo-plugin/lib/postbox/handler.php(239): Seravo\Postbox\Seravo_Postbox_Factory->display_single_postbox('site-info', Array)
#2 /data/wordpress/htdocs/wp-content/mu-plugins/seravo-plugin/lib/postbox/handler.php(280): Seravo\Postbox\Seravo_Postbox_Factory->do_postboxes('tools_page_site...', 'normal')
#3 /data/wordpress/htdocs/wp-content/mu-plugins/seravo-plugin/lib/postbox/handler.php(383): Seravo\Postbox\Seravo_Postbox_Factory->display_postboxes_page('four_column')
#4 /data/wordpress/htdocs/wordpress/wp-includes/class-wp-hook.php(292): Seravo\Postbox\seravo_postboxes_page('')
#5 /data/wordpress/htdocs/wordpress/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters('', Array)
#6 /data/wordpress/htdocs/wordpress/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#7 /data/wordpress/htdocs/wordpress/wp-admin/admin.php(259): do_action('tools_page_site...')
#8 /data/wordpress/htdocs/wordpress/wp-admin/tools.php(40): require_once('/data/wordpress...')
#9 {main}
  thrown in /data/wordpress/htdocs/wp-content/mu-plugins/seravo-plugin/modules/sitestatus.php on line 409
```

**Expected behavior**
These WP_Error instances should be caught.

**Comment by Moppa5** [comment]
Related to #544 as we should take care of this when rewriting the widgets.

**Comment by Moppa5** [comment]
Closing this in favor of #544 and #536. Issue #564 should take care of this as well.
